name: Adicionar Issue ao Quadro Central

on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    name: Adicionar Issue ao Quadro
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
      - name: Adicionar a issue ao quadro de projetos
        uses: actions/add-to-project@v1
        with:
          project-url: 'https://github.com/orgs/TRANSCORNEA/projects/2'
          github-token: ${{ secrets.GITHUB_TOKEN }}
